version: "3.8"
services:
  dcs-postgres:
    image: postgres
    container_name: postgres-ws-work
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data